// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ7b-fRBheePOu9yxVYXrFZ9mrQnlcbFM',
    appId: '1:526775744727:web:330aa3912f85f6c7d2d892',
    messagingSenderId: '526775744727',
    projectId: 'fire-notes-25',
    authDomain: 'fire-notes-25.firebaseapp.com',
    storageBucket: 'fire-notes-25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQnQ38kKNl0C7gjnkfNmN8EnHIUxnfJ_A',
    appId: '1:526775744727:android:10fa69c0bdf9739cd2d892',
    messagingSenderId: '526775744727',
    projectId: 'fire-notes-25',
    storageBucket: 'fire-notes-25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi_bl-CsaVbswN2uB_W8mcxElLcwS2p4E',
    appId: '1:526775744727:ios:0fcadbab3a1180a8d2d892',
    messagingSenderId: '526775744727',
    projectId: 'fire-notes-25',
    storageBucket: 'fire-notes-25.appspot.com',
    iosBundleId: 'com.insaneslayer25.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi_bl-CsaVbswN2uB_W8mcxElLcwS2p4E',
    appId: '1:526775744727:ios:0fcadbab3a1180a8d2d892',
    messagingSenderId: '526775744727',
    projectId: 'fire-notes-25',
    storageBucket: 'fire-notes-25.appspot.com',
    iosBundleId: 'com.insaneslayer25.notes',
  );
}
